### ISSUE TITLE
Run all archived migrations

### ISSUE THREAD

**Issue by kulla** [serlo/serlo-mysql-database#33]
After https://github.com/serlo/db-migrations/pull/296 we should run all archived migrations to update the local DB image. Do the following:

1. Run MySQL DB in this repository with `make up`.
2. Start Redis in `db-migrations`
3. Store in `dist` of `db-migrations` all archived migrations of the above PR (make sure only the migrations are stored there which shall be run)
4. Run them via https://github.com/serlo/db-migrations/blob/main/package.json#L27
5. Make a new dump via `make dump` and commit your changes.

**Comment by hejtful** [comment]
@kulla It seems like https://github.com/serlo/db-migrations/blob/main/package.json#L27 uses the `migrations` folder, so I used https://github.com/serlo/db-migrations/blob/main/package.json#L28 instead.
